sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary (arm 32bits)
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.9.1/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# build image
- docker build -t spanghf37/rpi-rf .
# test image
# - docker run spanghf37/rpi-rf uname -a
# push image
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker tag spanghf37/rpi-rf spanghf37/rpi-rf:arm32
- docker push spanghf37/rpi-rf:arm32
